#docker-compose up --build -d --remove-orphans

services:

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - task-management-volume:/data/postgres
    restart: unless-stopped
    networks:
      - task-management-network

  task-management-service:
    build:
      context: .
      dockerfile: task-management-service.dockerfile
    image: 'task-management-service:latest'
    container_name: 'task-management-service'
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - USER_EMAIL=${USER_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - task-management-network

volumes:
  task-management-volume:
    
networks:
  task-management-network:
    driver: bridge