#docker-compose up --build -d --remove-orphans

version: '3'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
    ports:
      - "5435:5432"
    volumes:
      - task-management-volume:/data/postgres
    restart: unless-stopped
    networks:
      - task-management-network

  task-management-service:
    build:
      context: .
      dockerfile: task-management-service.dockerfile
    image: 'task-management-service:latest'
    container_name: 'task-management-service'
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
    networks:
      - task-management-network

volumes:
  task-management-volume:
    
networks:
  task-management-network:
    driver: bridge